In [ ]:
import pandas as pd


def get_equity_returns(equity_log) -> pd.DataFrame:
    returns = []
    return returns


def get_hedge_returns():
    """ """
    # hedge_log = pd.read_csv("../dollat")
    # hedge_returns =


def compute_hedge_beta(equity_log):
    hedge_returns = get_hedge_returns
    pass

In [ ]:
df = pd.read_excel("./data/dollar_etf.xlsx", index_col="Dates")
df["returns"] = df["UUP US Equity"].pct_change()
df.drop("UUP US Equity", axis=1, inplace=True)
df.head()

             returns
Dates
2022-01-03       NaN
2022-01-04  0.000775
2022-01-05 -0.001162
2022-01-06  0.000776
2022-01-07 -0.005426

In [11]:
df.head()

             returns
Dates
2022-01-03       NaN
2022-01-04  0.000775
2022-01-05 -0.001162
2022-01-06  0.000776
2022-01-07 -0.005426

In [ ]:
import pandas as pd
from backtester_engine import Backtester

# Get signals data
train_predictions = pd.read_csv("./data/rf_train_predictions.csv", index_col="date")
test_predictions = pd.read_csv("./data/rf_test_predictions.csv", index_col="date")
entry_thresholds = pd.read_csv("./data/rf_thresholds.csv")
exit_thresholds = pd.read_csv("./data/rf_exit_thresholds.csv")
fx_contract_specs = pd.read_csv("./data/fx_contract_specs.csv")
fx_futures_panel = pd.read_csv("./data/fx_futures_panel.csv", index_col="date")


# Run backtesting simulation given parameters
backtester = Backtester(
    return_predictions=train_predictions,
    fx_futures_panel=fx_futures_panel,
    entry_thresholds=entry_thresholds,
    exit_thresholds=exit_thresholds,
    fx_contract_specs=fx_contract_specs,
    is_train=True,
    contract_cost_fixed=0.07,
    starting_equity=2_000_000,
    leverage_multiplier=5.0,
    hedge_positions=False,
)
backtester.run_backtest()

# Display results
backtest_trade_log, backtest_portfolio_log = backtester.get_backtest_results()
# print(backtest_portfolio_log, backtest_trade_log)
# print_portfolio_stats(backtest_portfolio_log)
# plot_portfolio_history(backtest_portfolio_log, backtest_trade_log)

# get strategy returns. It'll give me a return strream I'll regress against hte hedge asset

# get the hedge asset returns using dollar etf

# compute hedge beta

# hedge_beta = 0.0

# # Now compute hedge PnL
# hedge_bt = Backtester(return_predictions=train_predictions,
#                         fx_futures_panel=fx_futures_panel,
#                         entry_thresholds=entry_thresholds,
#                         exit_thresholds=exit_thresholds,
#                         fx_contract_specs=fx_contract_specs,
#                         is_train=True,
#                         contract_cost_fixed=0.07,
#                         starting_equity=2_000_000,
#                         leverage_multiplier=5.0,
#                         hedge_positions=True,
#                         hedge_ratio=hedge_beta)

Skipping 2022-01-31 Hong Kong because FX data missing
Skipping 2022-01-31 India because FX data missing
Skipping 2022-01-31 Singapore because FX data missing
Skipping 2022-02-01 Hong Kong because FX data missing
Skipping 2022-02-01 India because FX data missing
Skipping 2022-02-01 Singapore because FX data missing
Skipping 2022-02-02 Hong Kong because FX data missing
Skipping 2022-02-02 India because FX data missing
Skipping 2022-02-02 South Korea because FX data missing
Skipping 2022-02-02 Singapore because FX data missing
Skipping 2022-02-03 Hong Kong because FX data missing
Skipping 2022-02-03 India because FX data missing
Skipping 2022-02-03 Singapore because FX data missing
Skipping 2022-02-04 Hong Kong because FX data missing
Skipping 2022-02-04 India because FX data missing
Skipping 2022-02-04 Singapore because FX data missing
Skipping 2022-02-07 Hong Kong because FX data missing
Skipping 2022-02-07 India because FX data missing
Skipping 2022-02-07 South Korea because FX data missing
Skipping 2022-02-07 Singapore because FX data missing
Skipping 2022-02-08 Hong Kong because FX data missing
Skipping 2022-02-08 India because FX data missing
Skipping 2022-02-08 Singapore because FX data missing
Skipping 2022-02-09 Hong Kong because FX data missing
Skipping 2022-02-09 India because FX data missing
Skipping 2022-02-09 Singapore because FX data missing
Skipping 2022-02-10 Hong Kong because FX data missing
Skipping 2022-02-10 India because FX data missing
Skipping 2022-02-10 Singapore because FX data missing
Skipping 2022-02-11 Hong Kong because FX data missing
Skipping 2022-02-11 India because FX data missing
Skipping 2022-02-11 South Korea because FX data missing
Skipping 2022-02-11 Singapore because FX data missing
Skipping 2022-02-14 Hong Kong because FX data missing
Skipping 2022-02-14 India because FX data missing
Skipping 2022-02-14 Singapore because FX data missing
Skipping 2022-02-15 Hong Kong because FX data missing
Skipping 2022-02-15 India because FX data missing
Skipping 2022-02-15 South Korea because FX data missing
Skipping 2022-02-15 Singapore because FX data missing
Skipping 2022-02-16 Hong Kong because FX data missing
Skipping 2022-02-16 India because FX data missing
Skipping 2022-02-16 South Korea because FX data missing
Skipping 2022-02-16 Singapore because FX data missing
Skipping 2022-02-17 Hong Kong because FX data missing
Skipping 2022-02-17 India because FX data missing
Skipping 2022-02-17 South Korea because FX data missing
Skipping 2022-02-17 Singapore because FX data missing
Skipping 2022-02-18 Hong Kong because FX data missing
Skipping 2022-02-18 India because FX data missing
Skipping 2022-02-18 South Korea because FX data missing
Skipping 2022-02-18 Singapore because FX data missing
Skipping 2022-02-23 Hong Kong because FX data missing
Skipping 2022-02-23 India because FX data missing
Skipping 2022-02-23 Singapore because FX data missing
Skipping 2022-02-24 Hong Kong because FX data missing
Skipping 2022-02-24 India because FX data missing
Skipping 2022-02-24 South Korea because FX data missing
Skipping 2022-02-24 Singapore because FX data missing
Skipping 2022-02-25 Hong Kong because FX data missing
Skipping 2022-02-25 India because FX data missing
Skipping 2022-02-25 Singapore because FX data missing
Skipping 2022-02-28 Hong Kong because FX data missing
Skipping 2022-02-28 India because FX data missing
Skipping 2022-02-28 South Korea because FX data missing
Skipping 2022-02-28 Singapore because FX data missing
Skipping 2022-03-01 Hong Kong because FX data missing
Skipping 2022-03-01 India because FX data missing
Skipping 2022-03-01 Singapore because FX data missing
Skipping 2022-03-02 Hong Kong because FX data missing
Skipping 2022-03-02 India because FX data missing
Skipping 2022-03-02 Singapore because FX data missing
Skipping 2022-03-03 Hong Kong because FX data missing
Skipping 2022-03-03 India because FX data missing
Skipping 2022-03-03 Singapore because FX data missing
Skipping 2022-03-04 Hong Kong because FX data missing
Skipping 2022-03-04 India because FX data missing
Skipping 2022-03-04 South Korea because FX data missing
Skipping 2022-03-04 Singapore because FX data missing
Skipping 2022-03-07 Hong Kong because FX data missing
Skipping 2022-03-07 India because FX data missing
Skipping 2022-03-07 Singapore because FX data missing
Skipping 2022-03-08 Hong Kong because FX data missing
Skipping 2022-03-08 India because FX data missing
Skipping 2022-03-08 Singapore because FX data missing
Skipping 2022-03-09 Hong Kong because FX data missing
Skipping 2022-03-09 India because FX data missing
Skipping 2022-03-09 Singapore because FX data missing
Skipping 2022-03-10 Hong Kong because FX data missing
Skipping 2022-03-10 India because FX data missing
Skipping 2022-03-10 Singapore because FX data missing
Skipping 2022-03-11 Hong Kong because FX data missing
Skipping 2022-03-11 India because FX data missing
Skipping 2022-03-11 South Korea because FX data missing
Skipping 2022-03-11 Singapore because FX data missing
Skipping 2022-03-14 Hong Kong because FX data missing
Skipping 2022-03-14 India because FX data missing
Skipping 2022-03-14 Singapore because FX data missing
Skipping 2022-03-15 Hong Kong because FX data missing
Skipping 2022-03-15 India because FX data missing
Skipping 2022-03-15 Singapore because FX data missing
Skipping 2022-03-16 Hong Kong because FX data missing
Skipping 2022-03-16 India because FX data missing
Skipping 2022-03-16 Singapore because FX data missing
Skipping 2022-03-17 Hong Kong because FX data missing
Skipping 2022-03-17 India because FX data missing
Skipping 2022-03-17 Singapore because FX data missing
Skipping 2022-03-18 Mexico because FX data missing
Skipping 2022-03-18 Hong Kong because FX data missing
Skipping 2022-03-18 India because FX data missing
Skipping 2022-03-18 Singapore because FX data missing
Skipping 2022-03-21 Hong Kong because FX data missing
Skipping 2022-03-21 India because FX data missing
Skipping 2022-03-21 Singapore because FX data missing
Skipping 2022-03-22 Hong Kong because FX data missing
Skipping 2022-03-22 India because FX data missing
Skipping 2022-03-22 Singapore because FX data missing
Skipping 2022-03-23 Hong Kong because FX data missing
Skipping 2022-03-23 India because FX data missing
Skipping 2022-03-23 South Korea because FX data missing
Skipping 2022-03-23 Singapore because FX data missing
Skipping 2022-03-24 Hong Kong because FX data missing
Skipping 2022-03-24 India because FX data missing
Skipping 2022-03-24 Singapore because FX data missing
Skipping 2022-03-25 Mexico because FX data missing
Skipping 2022-03-25 Hong Kong because FX data missing
Skipping 2022-03-25 India because FX data missing
Skipping 2022-03-25 South Korea because FX data missing
Skipping 2022-03-25 Singapore because FX data missing
Skipping 2022-03-28 Hong Kong because FX data missing
Skipping 2022-03-28 India because FX data missing
Skipping 2022-03-28 South Korea because FX data missing
Skipping 2022-03-28 Singapore because FX data missing
Skipping 2022-03-29 Hong Kong because FX data missing
Skipping 2022-03-29 India because FX data missing
Skipping 2022-03-29 South Korea because FX data missing
Skipping 2022-03-29 Singapore because FX data missing
Skipping 2022-03-30 Hong Kong because FX data missing
Skipping 2022-03-30 India because FX data missing
Skipping 2022-03-30 South Korea because FX data missing
Skipping 2022-03-30 Singapore because FX data missing
Skipping 2022-03-31 Hong Kong because FX data missing
Skipping 2022-03-31 India because FX data missing
Skipping 2022-03-31 Singapore because FX data missing
Skipping 2022-04-01 Mexico because FX data missing
Skipping 2022-04-01 Hong Kong because FX data missing
Skipping 2022-04-01 India because FX data missing
Skipping 2022-04-01 South Korea because FX data missing
Skipping 2022-04-01 Singapore because FX data missing
Skipping 2022-04-06 Hong Kong because FX data missing
Skipping 2022-04-06 India because FX data missing
Skipping 2022-04-06 Singapore because FX data missing
Skipping 2022-04-07 Hong Kong because FX data missing
Skipping 2022-04-07 India because FX data missing
Skipping 2022-04-07 South Korea because FX data missing
Skipping 2022-04-07 Singapore because FX data missing
Skipping 2022-04-08 Hong Kong because FX data missing
Skipping 2022-04-08 India because FX data missing
Skipping 2022-04-08 South Korea because FX data missing
Skipping 2022-04-08 Singapore because FX data missing
Skipping 2022-04-11 Hong Kong because FX data missing
Skipping 2022-04-11 India because FX data missing
Skipping 2022-04-11 Singapore because FX data missing
Skipping 2022-04-12 Hong Kong because FX data missing
Skipping 2022-04-12 India because FX data missing
Skipping 2022-04-12 Singapore because FX data missing
Skipping 2022-04-13 Hong Kong because FX data missing
Skipping 2022-04-13 India because FX data missing
Skipping 2022-04-13 Singapore because FX data missing
Skipping 2022-04-14 Hong Kong because FX data missing
Skipping 2022-04-14 India because FX data missing
Skipping 2022-04-14 Singapore because FX data missing
Skipping 2022-04-15 Mexico because FX data missing
Skipping 2022-04-15 Brazil because FX data missing
Skipping 2022-04-15 South Africa because FX data missing
Skipping 2022-04-15 Japan because FX data missing
Skipping 2022-04-15 Australia because FX data missing
Skipping 2022-04-15 Canada because FX data missing
Skipping 2022-04-15 UK because FX data missing
Skipping 2022-04-15 Hong Kong because FX data missing
Skipping 2022-04-15 India because FX data missing
Skipping 2022-04-15 South Korea because FX data missing
Skipping 2022-04-15 Norway because FX data missing
Skipping 2022-04-15 Sweden because FX data missing
Skipping 2022-04-15 Singapore because FX data missing
Skipping 2022-04-15 Switzerland because FX data missing
Skipping 2022-04-15 New Zealand because FX data missing
Skipping 2022-04-18 Hong Kong because FX data missing
Skipping 2022-04-18 India because FX data missing
Skipping 2022-04-18 Singapore because FX data missing
Skipping 2022-04-19 Hong Kong because FX data missing
Skipping 2022-04-19 India because FX data missing
Skipping 2022-04-19 Singapore because FX data missing
Skipping 2022-04-20 Hong Kong because FX data missing
Skipping 2022-04-20 India because FX data missing
Skipping 2022-04-20 South Korea because FX data missing
Skipping 2022-04-20 Singapore because FX data missing
Skipping 2022-04-21 Hong Kong because FX data missing
Skipping 2022-04-21 India because FX data missing
Skipping 2022-04-21 South Korea because FX data missing
Skipping 2022-04-21 Singapore because FX data missing
Skipping 2022-04-22 Hong Kong because FX data missing
Skipping 2022-04-22 India because FX data missing
Skipping 2022-04-22 Singapore because FX data missing
Skipping 2022-04-25 Hong Kong because FX data missing
Skipping 2022-04-25 India because FX data missing
Skipping 2022-04-25 South Korea because FX data missing
Skipping 2022-04-25 Singapore because FX data missing
Skipping 2022-04-26 Hong Kong because FX data missing
Skipping 2022-04-26 India because FX data missing
Skipping 2022-04-26 Singapore because FX data missing
Skipping 2022-04-27 Hong Kong because FX data missing
Skipping 2022-04-27 India because FX data missing
Skipping 2022-04-27 Singapore because FX data missing
Skipping 2022-04-28 Hong Kong because FX data missing
Skipping 2022-04-28 India because FX data missing
Skipping 2022-04-28 Singapore because FX data missing
Skipping 2022-04-29 Hong Kong because FX data missing
Skipping 2022-04-29 India because FX data missing
Skipping 2022-04-29 South Korea because FX data missing
Skipping 2022-04-29 Singapore because FX data missing
Skipping 2022-05-02 Hong Kong because FX data missing
Skipping 2022-05-02 India because FX data missing
Skipping 2022-05-02 South Korea because FX data missing
Skipping 2022-05-02 Singapore because FX data missing
Skipping 2022-05-03 Hong Kong because FX data missing
Skipping 2022-05-03 India because FX data missing
Skipping 2022-05-03 South Korea because FX data missing
Skipping 2022-05-03 Singapore because FX data missing
Skipping 2022-05-04 Hong Kong because FX data missing
Skipping 2022-05-04 India because FX data missing
Skipping 2022-05-04 South Korea because FX data missing
Skipping 2022-05-04 Singapore because FX data missing
Skipping 2022-05-05 Hong Kong because FX data missing
Skipping 2022-05-05 India because FX data missing
Skipping 2022-05-05 South Korea because FX data missing
Skipping 2022-05-05 Singapore because FX data missing
Skipping 2022-05-06 Hong Kong because FX data missing
Skipping 2022-05-06 India because FX data missing
Skipping 2022-05-06 South Korea because FX data missing
Skipping 2022-05-06 Singapore because FX data missing
Skipping 2022-05-11 Hong Kong because FX data missing
Skipping 2022-05-11 India because FX data missing
Skipping 2022-05-11 Norway because FX data missing
Skipping 2022-05-11 Singapore because FX data missing
Skipping 2022-05-12 Hong Kong because FX data missing
Skipping 2022-05-12 India because FX data missing
Skipping 2022-05-12 Singapore because FX data missing
Skipping 2022-05-13 Hong Kong because FX data missing
Skipping 2022-05-13 India because FX data missing
Skipping 2022-05-13 South Korea because FX data missing
Skipping 2022-05-13 Singapore because FX data missing
Skipping 2022-05-16 Hong Kong because FX data missing
Skipping 2022-05-16 India because FX data missing
Skipping 2022-05-16 Singapore because FX data missing
Skipping 2022-05-17 Hong Kong because FX data missing
Skipping 2022-05-17 India because FX data missing
Skipping 2022-05-17 Singapore because FX data missing
Skipping 2022-05-18 Hong Kong because FX data missing
Skipping 2022-05-18 India because FX data missing
Skipping 2022-05-18 South Korea because FX data missing
Skipping 2022-05-18 Singapore because FX data missing
Skipping 2022-05-19 Hong Kong because FX data missing
Skipping 2022-05-19 India because FX data missing
Skipping 2022-05-19 South Korea because FX data missing
Skipping 2022-05-19 Singapore because FX data missing
Skipping 2022-05-20 Hong Kong because FX data missing
Skipping 2022-05-20 India because FX data missing
Skipping 2022-05-20 South Korea because FX data missing
Skipping 2022-05-20 Singapore because FX data missing
Skipping 2022-05-23 Hong Kong because FX data missing
Skipping 2022-05-23 India because FX data missing
Skipping 2022-05-23 South Korea because FX data missing
Skipping 2022-05-23 Singapore because FX data missing
Skipping 2022-05-24 Hong Kong because FX data missing
Skipping 2022-05-24 India because FX data missing
Skipping 2022-05-24 South Korea because FX data missing
Skipping 2022-05-24 Singapore because FX data missing
Skipping 2022-05-25 Hong Kong because FX data missing
Skipping 2022-05-25 India because FX data missing
Skipping 2022-05-25 Singapore because FX data missing
Skipping 2022-05-26 Hong Kong because FX data missing
Skipping 2022-05-26 India because FX data missing
Skipping 2022-05-26 Singapore because FX data missing
Skipping 2022-05-27 Hong Kong because FX data missing
Skipping 2022-05-27 India because FX data missing
Skipping 2022-05-27 Singapore because FX data missing
Skipping 2022-06-01 Hong Kong because FX data missing
Skipping 2022-06-01 India because FX data missing
Skipping 2022-06-01 South Korea because FX data missing
Skipping 2022-06-01 Singapore because FX data missing
Skipping 2022-06-02 Hong Kong because FX data missing
Skipping 2022-06-02 India because FX data missing
Skipping 2022-06-02 South Korea because FX data missing
Skipping 2022-06-02 Singapore because FX data missing
Skipping 2022-06-03 Hong Kong because FX data missing
Skipping 2022-06-03 India because FX data missing
Skipping 2022-06-03 South Korea because FX data missing
Skipping 2022-06-03 Singapore because FX data missing
Skipping 2022-06-06 Hong Kong because FX data missing
Skipping 2022-06-06 India because FX data missing
Skipping 2022-06-06 Singapore because FX data missing
Skipping 2022-06-07 Hong Kong because FX data missing
Skipping 2022-06-07 India because FX data missing
Skipping 2022-06-07 South Korea because FX data missing
Skipping 2022-06-07 Singapore because FX data missing
Skipping 2022-06-08 Hong Kong because FX data missing
Skipping 2022-06-08 India because FX data missing
Skipping 2022-06-08 Singapore because FX data missing
Skipping 2022-06-09 Hong Kong because FX data missing
Skipping 2022-06-09 India because FX data missing
Skipping 2022-06-09 Singapore because FX data missing
Skipping 2022-06-10 Hong Kong because FX data missing
Skipping 2022-06-10 India because FX data missing
Skipping 2022-06-10 Singapore because FX data missing
Skipping 2022-06-13 Hong Kong because FX data missing
Skipping 2022-06-13 India because FX data missing
Skipping 2022-06-13 Singapore because FX data missing
Skipping 2022-06-14 Hong Kong because FX data missing
Skipping 2022-06-14 India because FX data missing
Skipping 2022-06-14 South Korea because FX data missing
Skipping 2022-06-14 Singapore because FX data missing
Skipping 2022-06-15 Hong Kong because FX data missing
Skipping 2022-06-15 India because FX data missing
Skipping 2022-06-15 South Korea because FX data missing
Skipping 2022-06-15 Singapore because FX data missing
Skipping 2022-06-16 Hong Kong because FX data missing
Skipping 2022-06-16 India because FX data missing
Skipping 2022-06-16 Singapore because FX data missing
Skipping 2022-06-17 Hong Kong because FX data missing
Skipping 2022-06-17 India because FX data missing
Skipping 2022-06-17 Singapore because FX data missing
Skipping 2022-06-22 Hong Kong because FX data missing
Skipping 2022-06-22 India because FX data missing
Skipping 2022-06-22 Singapore because FX data missing
Skipping 2022-06-23 Hong Kong because FX data missing
Skipping 2022-06-23 India because FX data missing
Skipping 2022-06-23 Singapore because FX data missing
Skipping 2022-06-24 Hong Kong because FX data missing
Skipping 2022-06-24 India because FX data missing
Skipping 2022-06-24 South Korea because FX data missing
Skipping 2022-06-24 Singapore because FX data missing
Skipping 2022-06-27 Hong Kong because FX data missing
Skipping 2022-06-27 India because FX data missing
Skipping 2022-06-27 Singapore because FX data missing
Skipping 2022-06-28 Hong Kong because FX data missing
Skipping 2022-06-28 India because FX data missing
Skipping 2022-06-28 Singapore because FX data missing
Skipping 2022-06-29 Hong Kong because FX data missing
Skipping 2022-06-29 India because FX data missing
Skipping 2022-06-29 Singapore because FX data missing
Skipping 2022-06-30 Hong Kong because FX data missing
Skipping 2022-06-30 India because FX data missing
Skipping 2022-06-30 South Korea because FX data missing
Skipping 2022-06-30 Singapore because FX data missing
Skipping 2022-07-01 Hong Kong because FX data missing
Skipping 2022-07-01 India because FX data missing
Skipping 2022-07-01 Singapore because FX data missing
Skipping 2022-07-06 Hong Kong because FX data missing
Skipping 2022-07-06 India because FX data missing
Skipping 2022-07-06 Singapore because FX data missing
Skipping 2022-07-07 Hong Kong because FX data missing
Skipping 2022-07-07 India because FX data missing
Skipping 2022-07-07 South Korea because FX data missing
Skipping 2022-07-07 Singapore because FX data missing
Skipping 2022-07-08 Hong Kong because FX data missing
Skipping 2022-07-08 India because FX data missing
Skipping 2022-07-08 Singapore because FX data missing
Skipping 2022-07-13 Hong Kong because FX data missing
Skipping 2022-07-13 India because FX data missing
Skipping 2022-07-13 Singapore because FX data missing
Skipping 2022-07-14 Hong Kong because FX data missing
Skipping 2022-07-14 India because FX data missing
Skipping 2022-07-14 Singapore because FX data missing
Skipping 2022-07-15 Hong Kong because FX data missing
Skipping 2022-07-15 India because FX data missing
Skipping 2022-07-15 Singapore because FX data missing

In [13]:
df.set_index("date", inplace=True, drop=True)
df.index.name = None
print(df.columns)
df = df["equity"]
df.head()
# df.drop(["pl", "margin_used", "total_exposure", "target_asset_exposure"], axis=1, inplace=True)

KeyError: "None of ['date'] are in the columns"

In [8]:
df = pd.DataFrame(portfolio_log)
df.set_index("date", inplace=True, drop=True)
df.index.name = None
print(df.columns)
df = df["equity"]
df.drop(
    ["pl", "margin_used", "total_exposure", "target_asset_exposure"],
    axis=1,
    inplace=True,
)

NameError: name 'portfolio_log' is not defined

In [ ]:
import numpy as np


def get_equity_returns(portfolio_log) -> pd.DataFrame:
    df = pd.DataFrame(portfolio_log)
    df.set_index("date", inplace=True, drop=True)
    df.index.name = None
    df.drop(
        ["pl", "margin_used", "total_exposure", "target_asset_exposure"],
        axis=1,
        inplace=True,
    )
    df.columns = ["equity"]
    df["equity_returns"] = df["equity"].pct_change()
    df.drop("equity", axis=1, inplace=True)
    df.head()
    return df


def get_hedge_returns():
    """ """
    df = pd.read_excel("./data/dollar_etf.xlsx", index_col="Dates")
    df["hedge_returns"] = df["UUP US Equity"].pct_change()
    df.drop("UUP US Equity", axis=1, inplace=True)
    return df


hedge_returns = get_hedge_returns()
equity_returns = get_equity_returns(backtest_portfolio_log)
equity_returns.index = pd.to_datetime(equity_returns.index)

In [ ]:
hedge_returns.index

DatetimeIndex(['2022-01-03', '2022-01-04', '2022-01-05', '2022-01-06',
               '2022-01-07', '2022-01-10', '2022-01-11', '2022-01-12',
               '2022-01-13', '2022-01-14',
               ...
               '2026-02-19', '2026-02-20', '2026-02-23', '2026-02-24',
               '2026-02-25', '2026-02-26', '2026-02-27', '2026-03-02',
               '2026-03-03', '2026-03-04'],
              dtype='datetime64[us]', name='Dates', length=1045, freq=None)

In [ ]:
equity_returns.index

DatetimeIndex(['2022-01-31', '2022-02-01', '2022-02-02', '2022-02-03',
               '2022-02-04', '2022-02-07', '2022-02-08', '2022-02-09',
               '2022-02-10', '2022-02-11',
               ...
               '2024-09-10', '2024-09-11', '2024-09-12', '2024-09-17',
               '2024-09-18', '2024-09-19', '2024-09-20', '2024-09-23',
               '2024-09-24', '2024-09-25'],
              dtype='datetime64[us]', length=589, freq=None)

In [ ]:
df = hedge_returns.merge(equity_returns, left_index=True, right_index=True, how="inner")
df.head()

            hedge_returns  equity_returns
Dates
2022-01-31      -0.006910             NaN
2022-02-01      -0.002706             0.0
2022-02-02      -0.003876             0.0
2022-02-03      -0.005058             0.0
2022-02-04      -0.000782             0.0

In [ ]:
clean_df = df[["equity_returns", "hedge_returns"]].dropna()

# Check if you still have data left!
if not clean_df.empty:
    beta, alpha = np.polyfit(clean_df["equity_returns"], clean_df["hedge_returns"], 1)
    print(f"Beta: {beta}")
else:
    print("Error: No overlapping data points after dropping NaNs.")

Beta: -0.6094272968512179